### ISSUE TITLE
Video records of TD1

### ISSUE THREAD

**Issue by YarikSWT** [IUT-Blagnac/design-pattern-td1#1]
Dear Professor  @jmbruel, 

Could you please publish the records of the last TDs, which you recorded by the Zoom?
To make your life easier we looked to the history of recordings and the video should be stored at /Users/jmb/Documents/Zoom/2020-11-03 17.34.16 IPOD-F20 88603699295/ at your computer.

Meilleurs sentiments

**Comment by Rinatum** [comment]
> Dear Professor,
> 
> Could you please publish the records of the last TDs, which you recorded by the Zoom?
> To make your life easier we looked to the history of recordings and the video should be stored at /Users/jmb/Documents/Zoom/2020-11-03 17.34.16 IPOD-F20 88603699295/ at your computer.
> 
> Meilleurs sentiments

Yeah
I accept this solution

**Comment by jmbruel** [comment]
Thanks. I've sent the link on Telegram.
